id = "sublime-mariana-theme"
name = "Sublime Mariana Theme"
version = "1.1.4"
schema_version = 1
authors = ["Roman Hnatiuk<roman@hnatiuk.cc>"]
description = "Theme for Zed Editor that imitates Sublime Text 4's Mariana colour scheme."
repository = "https://github.com/hnatiukr/zed-mariana-theme"
